#!/usr/bin/env bash
# Start DBack Control Plane + Web UI (dev or prod).
#
# Dev (default): API on :14127, Vite on :5173 (proxies /api → API).
# Prod (--prod): builds web/dist and serves SPA + API from a single process.
#
# Usage:
#   ./run-web.sh              # dev mode
#   ./run-web.sh --prod       # production-style single server
#   ./run-web.sh --debug      # enable DBACK_DEBUG on API
#   ./run-web.sh --help

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

DEV_DIR="${ROOT}/.dev"
DATA_DIR="${DBACK_DATA_DIR:-${DEV_DIR}/data}"
LISTEN="${DBACK_LISTEN:-127.0.0.1:14127}"
PASSPHRASE="${DBACK_PASSPHRASE:-dev-passphrase}"
API_TOKEN="${DBACK_API_TOKEN:-dev-token}"
SERVER_BIN="${ROOT}/dist/dback-server"
WEB_DIR="${ROOT}/web"
VITE_PORT="${DBACK_VITE_PORT:-5173}"

MODE=dev
DEBUG=false
SKIP_GO_BUILD=false
SKIP_NPM_INSTALL=false

SERVER_PID=""
CHILD_PID=""

usage() {
	cat <<'EOF'
Usage: ./run-web.sh [options]

Options:
  --prod            Build web/dist and serve SPA + API from dback serve (no Vite)
  --debug           Set DBACK_DEBUG=1 on the API server
  --no-build        Skip rebuilding dist/dback-server
  --no-install      Skip npm ci/install in web/
  -h, --help        Show this help

Environment (optional overrides):
  DBACK_DATA_DIR       Vault/data directory (default: .dev/data)
  DBACK_PASSPHRASE     Vault passphrase (default: dev-passphrase)
  DBACK_API_TOKEN      Bearer token for /api/v1 (default: dev-token)
  DBACK_LISTEN         API bind address (default: 127.0.0.1:14127)
  DBACK_VITE_PORT      Vite dev port (default: 5173)

Dev:  open http://127.0.0.1:5173 and paste the API token when prompted.
Prod: open http://127.0.0.1:14127 (or DBACK_LISTEN host/port).
EOF
}

for arg in "$@"; do
	case "$arg" in
		--prod) MODE=prod ;;
		--debug) DEBUG=true ;;
		--no-build) SKIP_GO_BUILD=true ;;
		--no-install) SKIP_NPM_INSTALL=true ;;
		-h|--help)
			usage
			exit 0
			;;
		*)
			echo "Unknown option: $arg" >&2
			usage >&2
			exit 2
			;;
	esac
done

require_cmd() {
	if ! command -v "$1" >/dev/null 2>&1; then
		echo "ERROR: '$1' is required but not installed." >&2
		exit 1
	fi
}

# Stop a previous dback serve still bound to LISTEN (common after rebuild while old PID keeps running).
stop_existing_server() {
	local port="${LISTEN##*:}"
	if command -v fuser >/dev/null 2>&1; then
		if fuser "${port}/tcp" >/dev/null 2>&1; then
			echo "==> Stopping existing listener on port ${port}..."
			fuser -k "${port}/tcp" 2>/dev/null || true
			sleep 0.4
		fi
	fi
	if pgrep -f "${SERVER_BIN} serve" >/dev/null 2>&1; then
		pkill -f "${SERVER_BIN} serve" 2>/dev/null || true
		sleep 0.3
	fi
}

cleanup() {
	local code="${1:-0}"
	if [[ -n "$CHILD_PID" ]] && kill -0 "$CHILD_PID" 2>/dev/null; then
		kill "$CHILD_PID" 2>/dev/null || true
		wait "$CHILD_PID" 2>/dev/null || true
	fi
	if [[ -n "$SERVER_PID" ]] && kill -0 "$SERVER_PID" 2>/dev/null; then
		kill "$SERVER_PID" 2>/dev/null || true
		wait "$SERVER_PID" 2>/dev/null || true
	fi
	exit "$code"
}

trap 'cleanup 130' INT TERM

require_cmd go
require_cmd node
require_cmd npm

mkdir -p "$DEV_DIR" "$DATA_DIR"

if [[ "$SKIP_GO_BUILD" != true ]] || [[ ! -x "$SERVER_BIN" ]]; then
	echo "==> Building headless server (dist/dback-server)..."
	go build -o "$SERVER_BIN" ./cmd/dback
fi

stop_existing_server

if [[ "$SKIP_NPM_INSTALL" != true ]]; then
	echo "==> Installing web dependencies..."
	if [[ -f "$WEB_DIR/package-lock.json" ]]; then
		( cd "$WEB_DIR" && npm ci )
	else
		( cd "$WEB_DIR" && npm install )
	fi
fi

export DBACK_DATA_DIR="$DATA_DIR"
export DBACK_PASSPHRASE="$PASSPHRASE"
export DBACK_API_TOKEN="$API_TOKEN"
export DBACK_LISTEN="$LISTEN"
if [[ "$DEBUG" == true ]]; then
	export DBACK_DEBUG=1
fi

if [[ "$MODE" == prod ]]; then
	echo "==> Building web for production..."
	( cd "$WEB_DIR" && npm run build )
	export DBACK_WEB_ROOT="${DBACK_WEB_ROOT:-${WEB_DIR}/dist}"
	echo ""
	echo "DBack Control Plane (prod)"
	echo "  URL:    http://${LISTEN/127.0.0.1/localhost}"
	echo "  Token:  $API_TOKEN"
	echo "  Data:   $DATA_DIR"
	echo ""
	exec "$SERVER_BIN" serve
fi

echo "==> Starting API server on $LISTEN ..."
"$SERVER_BIN" serve &
SERVER_PID=$!

# Wait until /health/live responds (max ~15s). Falls back to a short delay if curl is missing.
ready=false
if command -v curl >/dev/null 2>&1; then
	for _ in $(seq 1 30); do
		if curl -sf "http://${LISTEN}/health/live" >/dev/null 2>&1; then
			ready=true
			break
		fi
		if ! kill -0 "$SERVER_PID" 2>/dev/null; then
			echo "ERROR: dback serve exited unexpectedly." >&2
			wait "$SERVER_PID" || true
			exit 1
		fi
		sleep 0.5
	done
else
	sleep 1
	if kill -0 "$SERVER_PID" 2>/dev/null; then
		ready=true
	fi
fi
if [[ "$ready" != true ]]; then
	echo "ERROR: API did not become ready on $LISTEN" >&2
	cleanup 1
fi

cat >"${DEV_DIR}/credentials.env" <<EOF
# Generated by run-web.sh — local dev only
DBACK_DATA_DIR=$DATA_DIR
DBACK_PASSPHRASE=$PASSPHRASE
DBACK_API_TOKEN=$API_TOKEN
DBACK_LISTEN=$LISTEN
EOF

echo ""
echo "DBack Web (dev)"
echo "  UI:     http://127.0.0.1:${VITE_PORT}"
echo "  API:    http://${LISTEN}"
echo "  Token:  $API_TOKEN"
echo "  Data:   $DATA_DIR"
echo "  Creds:  ${DEV_DIR}/credentials.env"
echo ""
echo "Press Ctrl+C to stop API + Vite."
echo ""

( cd "$WEB_DIR" && npm run dev -- --host 127.0.0.1 --port "$VITE_PORT" ) &
CHILD_PID=$!

wait "$CHILD_PID" || true
cleanup 0
