package wordpress

import (
	"archive/zip"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
)

const pluginTemplate = `<?php

/**
 * Plugin Name: DB Sync Connector
 * Description: generated by DB Sync Manager App. Handles database export/import securely.
 * Version: 1.6
 * Author: DB Sync Manager
 */

if (!defined('ABSPATH')) {
  exit;
}

define('DBACK_API_KEY', '{{API_KEY}}');

class DBack_Sync_API {

  public function __construct() {
    add_action('rest_api_init', array($this, 'register_routes'));
  }

  public function register_routes() {
    // Ping endpoint for connectivity testing
    register_rest_route('dback/v1', '/ping', array(
      'methods' => 'GET',
      'callback' => array($this, 'handle_ping'),
      'permission_callback' => array($this, 'check_permission'),
    ));

    register_rest_route('dback/v1', '/export', array(
      'methods' => 'GET',
      'callback' => array($this, 'handle_export'),
      'permission_callback' => array($this, 'check_permission'),
    ));

    register_rest_route('dback/v1', '/import', array(
      'methods' => 'POST',
      'callback' => array($this, 'handle_import'),
      'permission_callback' => array($this, 'check_permission'),
    ));
  }

  public function check_permission($request) {
    $auth_header = $request->get_header('X-DBACK-KEY');
    if ($auth_header !== DBACK_API_KEY) {
      return new WP_Error('rest_forbidden', 'Invalid or missing API key', array('status' => 403));
    }
    return true;
  }

  /**
   * Handle ping request - returns server info for debugging
   */
  public function handle_ping($request) {
    global $wpdb;
    
    $info = array(
      'success' => true,
      'message' => 'DBack Sync plugin is active and ready',
      'version' => '1.6',
      'php_version' => PHP_VERSION,
      'wp_version' => get_bloginfo('version'),
      'can_use_shell' => $this->can_use_shell(),
      'shell_functions_disabled' => ini_get('disable_functions'),
      'db_connected' => ($wpdb->check_connection(false) !== false),
      'upload_dir_writable' => is_writable(wp_upload_dir()['basedir']),
      'memory_limit' => ini_get('memory_limit'),
      'max_execution_time' => ini_get('max_execution_time'),
    );
    
    return rest_ensure_response($info);
  }

  /**
   * Safe replacement for escapeshellarg() if disabled by host
   */
  private function safe_arg($string) {
    if (function_exists('escapeshellarg')) {
      return escapeshellarg($string);
    }
    // Fallback: wrap in single quotes and escape existing single quotes
    return "'" . str_replace("'", "'\\''", $string) . "'";
  }

  /**
   * Check if shell execution is available
   */
  private function can_use_shell() {
    return function_exists('exec') && !in_array('exec', array_map('trim', explode(',', ini_get('disable_functions'))));
  }

  public function handle_export($request) {
    // Increase limits
    @set_time_limit(0);
    @ini_set('memory_limit', '512M');

    global $wpdb;
    
    // Verify upload directory is writable
    $upload_dir = wp_upload_dir();
    if (!is_writable($upload_dir['basedir'])) {
      return new WP_Error('export_failed', 'Upload directory is not writable: ' . $upload_dir['basedir'], array('status' => 500));
    }
    
    $dump_file = $upload_dir['basedir'] . '/dback_dump_' . time() . '.sql.gz';

    // 1. Try System Shell (mysqldump) if allowed
    $shell_success = false;
    $shell_error = '';

    if ($this->can_use_shell()) {
        $db_name = DB_NAME;
        $db_user = DB_USER;
        $db_pass = DB_PASSWORD;
        $db_host = DB_HOST;

        $cmd = sprintf(
          'mysqldump -h %s -u %s -p%s %s 2>&1 | gzip > %s',
          $this->safe_arg($db_host),
          $this->safe_arg($db_user),
          $this->safe_arg($db_pass),
          $this->safe_arg($db_name),
          $this->safe_arg($dump_file)
        );

        @exec($cmd, $output, $return_var);

        if ($return_var === 0 && file_exists($dump_file) && filesize($dump_file) > 100) {
            $shell_success = true;
        } else {
            $shell_error = "mysqldump exit code: $return_var, output: " . implode("\n", $output);
            // Clean up failed dump file
            if (file_exists($dump_file)) {
                @unlink($dump_file);
            }
        }
    }

    // 2. Fallback to PHP Native Export if shell failed or is disabled
    if (!$shell_success) {
        $res = $this->export_php_native($dump_file);
        if (is_wp_error($res)) {
            // Include shell error info if available
            if ($shell_error) {
                return new WP_Error('export_failed', 
                  'Both mysqldump and PHP export failed. Shell error: ' . $shell_error . '. PHP error: ' . $res->get_error_message(), 
                  array('status' => 500));
            }
            return $res;
        }
    }

    // Stream file download
    if (!file_exists($dump_file)) {
      $err_msg = 'Dump file generation failed.';
      if ($shell_error) {
        $err_msg .= ' Shell error: ' . $shell_error;
      }
      return new WP_Error('export_failed', $err_msg, array('status' => 500));
    }

    $file_size = filesize($dump_file);
    
    // Validate file is not too small (would indicate an error)
    if ($file_size < 100) {
      $content = @file_get_contents($dump_file);
      @unlink($dump_file);
      return new WP_Error('export_failed', 'Dump file too small (' . $file_size . ' bytes). Content: ' . $content, array('status' => 500));
    }

    // Clean buffer
    while (ob_get_level()) {
        ob_end_clean();
    }

    header('Content-Description: File Transfer');
    header('Content-Type: application/gzip');
    header('Content-Disposition: attachment; filename=' . basename($dump_file));
    header('Content-Length: ' . $file_size);
    header('Expires: 0');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');

    readfile($dump_file);

    // Delete after send
    unlink($dump_file);
    exit;
  }

  /**
   * Escape a value for SQL - uses mysqli_real_escape_string directly
   * to avoid WordPress esc_sql() issues with special characters like %
   */
  private function sql_escape($val) {
      global $wpdb;
      if ($val === null) {
          return 'NULL';
      }
      // Use mysqli_real_escape_string directly to avoid esc_sql() issues with %
      if (isset($wpdb->dbh) && ($wpdb->dbh instanceof mysqli)) {
          return "'" . mysqli_real_escape_string($wpdb->dbh, $val) . "'";
      }
      // Fallback: manual escaping
      $escaped = str_replace(
          array("\\", "\x00", "\n", "\r", "'", '"', "\x1a"),
          array("\\\\", "\\0", "\\n", "\\r", "\\'", '\\"', "\\Z"),
          $val
      );
      return "'" . $escaped . "'";
  }

  /**
   * PHP-based fallback for generating SQL dump
   */
  private function export_php_native($filepath) {
      global $wpdb;

      $fp = gzopen($filepath, 'w9');
      if (!$fp) {
          return new WP_Error('export_failed', 'Cannot open file for writing. Check permissions.', array('status' => 500));
      }

      $tables = $wpdb->get_col("SHOW TABLES");

      foreach ($tables as $table) {
          // Get Create Table
          $create_table = $wpdb->get_row("SHOW CREATE TABLE ` + "`" + `$table` + "`" + `", ARRAY_N);
          gzwrite($fp, "DROP TABLE IF EXISTS ` + "`" + `$table` + "`" + `;\n");
          gzwrite($fp, $create_table[1] . ";\n\n");

          // Get column names for proper INSERT syntax
          $columns = $wpdb->get_results("SHOW COLUMNS FROM ` + "`" + `$table` + "`" + `", ARRAY_N);
          $column_names = array();
          foreach ($columns as $col) {
              $column_names[] = "` + "`" + `" . $col[0] . "` + "`" + `";
          }
          $columns_str = implode(', ', $column_names);

          // Get Data using unbuffered query via mysqli
          if (isset($wpdb->dbh) && ($wpdb->dbh instanceof mysqli)) {
              $result = mysqli_query($wpdb->dbh, "SELECT * FROM ` + "`" + `$table` + "`" + `", MYSQLI_USE_RESULT);
              if ($result) {
                  while ($row = mysqli_fetch_row($result)) {
                      $values = array();
                      foreach ($row as $val) {
                          $values[] = $this->sql_escape($val);
                      }
                      gzwrite($fp, "INSERT INTO ` + "`" + `$table` + "`" + ` ($columns_str) VALUES (" . implode(',', $values) . ");\n");
                  }
                  mysqli_free_result($result);
              }
          } else {
             // Fallback for older systems (high memory usage)
             $rows = $wpdb->get_results("SELECT * FROM ` + "`" + `$table` + "`" + `", ARRAY_N);
             foreach ($rows as $row) {
                 $values = array();
                 foreach ($row as $val) {
                     $values[] = $this->sql_escape($val);
                 }
                 gzwrite($fp, "INSERT INTO ` + "`" + `$table` + "`" + ` ($columns_str) VALUES (" . implode(',', $values) . ");\n");
             }
          }
          gzwrite($fp, "\n");
      }

      gzclose($fp);
      return true;
  }

  public function handle_import($request) {
    @set_time_limit(0);

    global $wpdb;

    // Check if shell is possible
    if (!$this->can_use_shell()) {
        return new WP_Error('import_failed', 'Server shell access is disabled. Cannot run mysql import command.', array('status' => 500));
    }

    $db_name = DB_NAME;
    $db_user = DB_USER;
    $db_pass = DB_PASSWORD;
    $db_host = DB_HOST;

    $upload_dir = wp_upload_dir()['basedir'];
    $temp_file = $upload_dir . '/dback_import_' . time() . '.sql.gz';

    // Write input to temp file
    $input = fopen('php://input', 'rb');
    $file = fopen($temp_file, 'wb');
    stream_copy_to_stream($input, $file);
    fclose($input);
    fclose($file);

    $cmd = sprintf(
      'gunzip -c %s | mysql -h %s -u %s -p%s %s',
      $this->safe_arg($temp_file),
      $this->safe_arg($db_host),
      $this->safe_arg($db_user),
      $this->safe_arg($db_pass),
      $this->safe_arg($db_name)
    );

    @exec($cmd, $output, $return_var);

    if (file_exists($temp_file)) unlink($temp_file);

    if ($return_var !== 0) {
      return new WP_Error('import_failed', 'mysql command failed', array('status' => 500));
    }

    return rest_ensure_response(array('success' => true, 'message' => 'Database imported successfully'));
  }
}

new DBack_Sync_API();`

// GeneratePlugin creates a WP plugin zip with a unique key
func GeneratePlugin(templatePath, destDir string) (string, string, error) {
	// Generate Key
	key, err := generateKey()
	if err != nil {
		return "", "", err
	}

	// Use embedded template
	content := pluginTemplate

	// Replace Key
	pluginCode := strings.ReplaceAll(content, "{{API_KEY}}", key)

	// Create Zip
	zipPath := fmt.Sprintf("%s/dback-sync-plugin.zip", destDir)
	file, err := os.Create(zipPath)
	if err != nil {
		return "", "", err
	}
	defer file.Close()

	w := zip.NewWriter(file)
	defer w.Close()

	// Add file to zip
	f, err := w.Create("dback-sync/dback-sync.php")
	if err != nil {
		return "", "", err
	}
	_, err = f.Write([]byte(pluginCode))
	if err != nil {
		return "", "", err
	}

	return key, zipPath, nil
}

func generateKey() (string, error) {
	bytes := make([]byte, 32)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}
